- name: Bzaf Main
  hosts: undercloud
  gather_facts: yes
  any_errors_fatal: yes
  vars:
    dir: "{{ ansible_env.HOME }}/bzaf"
    venv: "{{ ansible_env.HOME }}/bzaf_venv"
    python_ver: "{{ (overcloud_version|openstack_release >= 15) | ternary('python3', 'python') }}"

  tasks:

        - name: Install Bzaf
          include_tasks: tasks/install.yml

        - name: Run Bzaf
          include_tasks: tasks/run.yml
