- name: Bzaf Main
  hosts: undercloud
  gather_facts: yes
  any_errors_fatal: yes
  vars:
    dir: "{{ ansible_env.HOME }}/bzaf"
    venv: "{{ ansible_env.HOME }}/bzaf_venv"
  tasks:

        - name: Install Bzaf
          include_tasks: tasks/install.yml

        - name: Run Bzaf
          include_tasks: tasks/run.yml
