- name: Bzaf Main
  hosts: undercloud
  gather_facts: yes
  ignore_errors: true
  vars:
    dir: "{{ ansible_env.HOME }}/bzaf"
    venv: "{{ ansible_env.HOME }}/bzaf_venv"
    python_ver: python{{ansible_python.version.major}}

  tasks:

        - name: output job id and time of execution
          include_tasks: tasks/ci_job_id.yml

        - name: Install Bzaf
          include_tasks: tasks/install.yml

        - name: Run Bzaf
          include_tasks: tasks/run.yml
